server:
  port: 8085
spring:
  application:
    name: ms-api-client
  cloud:
    gateway:
      routes:
        - id: ms-client-1
          uri: http://localhost:8081
          predicates:
            - Path=/load/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka